import one from "./images/1.JPG";
import two from "./images/2.JPG";
import three from "./images/3.JPG";
import four from "./images/4.jpg";
import five from "./images/5.JPG";
import six from "./images/6.jpg";
import seven from "./images/7.JPG";
import eight from "./images/8.JPG";
import nine from "./images/9.JPG";
import ten from "./images/10.JPG";
import eleven from "./images/11.JPG";
import twelve from "./images/12.JPG";
import thirteen from "./images/13.JPG";
import fourteen from "./images/14.JPG";
import fifteen from "./images/15.JPG";
import sixteen from "./images/16.JPG";
import seventeen from "./images/17.JPG";
import eighteen from "./images/18.jpg";
import nineteen from "./images/19.JPG";
import twenty from "./images/20.JPG";
import twentyOne from "./images/21.jpg";
import twentyTwo from "./images/22.JPG";
import twentyThree from "./images/23.JPG";
import twentyFour from "./images/24.JPG";
import twentyFive from "./images/25.JPG";

const response = [
  {
    id: 1,
    name: "Native Signature Long Shorts",
    price: "20,000",
    img: one,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "grey", "green"],
    sizes: ["XS", "S", "M", "XL", "2XL", "3XL"],
    categories: ["men", "All"],
  },
  {
    id: 2,
    name: "Native Signature Beach Shorts",
    price: "40,000",
    img: two,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["women", "All"],
  },
  {
    id: 3,
    name: "Native Signature Italian Beach Shorts",
    price: "140,000",
    img: three,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["brown", "black", "red", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 4,
    name: "Native Signature Knee Shorts",
    price: "460,000",
    img: four,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "white"],
    sizes: ["XS", "S", "M", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 5,
    name: "Native Signature Ankara Jacket",
    price: "130,000",
    img: five,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "green"],
    sizes: ["XS", "S", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 6,
    name: "Native Signature Jump Suit",
    price: "20,000",
    img: six,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["white", "black", "green"],
    sizes: ["XS", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 7,
    name: "Native Signature Ankara Sweat Pants",
    price: "50,000",
    img: seven,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "pink", "green"],
    sizes: ["XS", "S", "XL", "2XL", "3XL"],
    categories: ["men", "All"],
  },
  {
    id: 8,
    name: "Native Signature Sweat Suit",
    price: "550,000",
    img: eight,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["red", "black", "teal", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 9,
    name: "Native Signature Ankara Dress",
    price: "80,000",
    img: nine,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 10,
    name: "Native Signature Sleeveless Jacket",
    price: "90,000",
    img: ten,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 11,
    name: "Native Signature Timely Tshirt",
    price: "40,000",
    img: eleven,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "red", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All"],
  },
  {
    id: 12,
    name: "Native Signature  Redux Tshirt",
    price: "180,000",
    img: twelve,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "gray", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 13,
    name: "Native Signature Custom  Tshirt",
    price: "50,000",
    img: thirteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["red", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 14,
    name: "Native Signature Ankara Dual Jacket",
    price: "80,000",
    img: fourteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 15,
    name: "Native Signature Jean Jacket",
    price: "60,000",
    img: fifteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    categories: ["men", "women", "All", "newest"],
  },

  {
    id: 16,
    name: "Native Signature Italian Knee Shorts",
    price: "220,000",
    img: sixteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "green"],
    sizes: ["XS", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 17,
    name: "Native Signature Ankara Vest Jacket",
    price: "80,000",
    img: seventeen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["red", "black", "purple", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 18,
    name: "Native Signature Ankara Sweat Suit",
    price: "60,000",
    img: eighteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["purple", "black", "blue", "green"],
    sizes: ["XS", "S", "M", "L", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 19,
    name: "Native Signature Ankara Sweat Shorts",
    price: "70,000",
    img: nineteen,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "teal", "green"],
    sizes: ["XS", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 20,
    name: "Native Signature Ankara Leather jacket",
    price: "30,000",
    img: twenty,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "purple", "white"],
    sizes: ["XS", "S", "M", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 21,
    name: "Native Signature Ankara Top Hat",
    price: "60,000",
    img: twentyOne,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "pink", "green"],
    sizes: ["XS", "S", "M", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest", "accessories"],
  },
  {
    id: 22,
    name: "Native Signature Ankara Loose Pants",
    price: "80,000",
    img: twentyTwo,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "red", "green"],
    sizes: ["XS", "S", "M", "L", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 23,
    name: "Native Signature Beach Shorts",
    price: "140,000",
    img: twentyThree,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["red", "black", "blue", "green"],
    sizes: ["XS", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 24,
    name: "Native Signature Long Sleeved Shirt",
    price: "350,000",
    img: twentyFour,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["pink", "black", "blue", "white"],
    sizes: ["XS", "S", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
  {
    id: 25,
    name: "Native Signature Ankara Tight Shorts",
    price: "220,000",
    img: twentyFive,
    description: "lorem ipsum dolor sit amet, consectetur adip",
    colors: ["teal", "black", "pink", "green"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    categories: ["men", "women", "All", "newest"],
  },
];
export default response;
